# Generated by Django 3.1.1 on 2020-09-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_id',
            new_name='id',
        ),
    ]
