# Generated by Django 3.1.1 on 2020-09-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200905_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='option_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
        migrations.AddField(
            model_name='option',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
